export const  booksActions={
    BOOKS_LOADING:"BOOKS_LOADING",
    BOOKS_LOADING_FAILED:"BOOKS_LOADING_FAILED",
    GET_ALL_BOOKS:"GET_ALL_BOOKS",
    GET_SPECIFIC_BOOK:"GET_SPECIFIC_BOOK",
    POST_BOOK:"POST_BOOK",
    UPDATE_BOOK:"UPDATE_BOOK",
    DELETE_BOOK:"DELETE_BOOK",
    SEARCH_BOOKS:"SEARCH_BOOKS"
}